name: DevSecOps Security Scan

on:
  push:

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -x tests

      - name: Run Trivy File Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
