name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          pip install flask bandit

      # ------------------------
      # Bandit SAST Scan
      # ------------------------
      - name: Run Bandit Scan
        run: bandit -r . -x tests

      # ------------------------
      # Trivy Filesystem Scan
      # ------------------------
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .

      # ------------------------
      # Gitleaks Secret Scan
      # ------------------------
      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2

      # ------------------------
      # Build Docker Image
      # ------------------------
      - name: Build Docker Image
        run: docker build -t devsecops-app .

      # ------------------------
      # Trivy Image Scan
      # ------------------------
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: devsecops-app

      # ------------------------
      # Run Flask App
      # ------------------------
      - name: Start Flask App
        run: |
          python app.py &
          sleep 10

      # ------------------------
      # OWASP ZAP DAST Scan
      # ------------------------
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:5000"
